version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_DB_USER_NAME: postgres
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
